AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create IAM role with specified policies'

Resources:
  AWSChronicleRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: awschronicle
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonSSMPatchAssociation
        - arn:aws:iam::aws:policy/ROSAKMSProviderPolicy
        - !Ref PatchPolicyBaselineOverridesPolicy

  PatchPolicyBaselineOverridesPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: aws-quicksetup-patchpolicy-baselineoverrides-s3
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - arn:aws:s3:::aws-quicksetup-patchpolicy/*

Outputs:
  RoleARN:
    Description: ARN of the created IAM Role
    Value: !GetAtt AWSChronicleRole.Arn
  
  RoleName:
    Description: Name of the created IAM Role
    Value: !Ref AWSChronicleRole
  
  CustomPolicyArn:
    Description: ARN of the custom policy
    Value: !Ref PatchPolicyBaselineOverridesPolicy
