name: Deploy CloudFormation Stack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Optional: Enable manual triggers
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents
        run: |
          pwd
          ls -la
          ls -la euc-platform/cloudformation || echo "Cloudformation directory not found"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACCESS_KEY }}
          aws-region: ${{ secrets.ACCESS_KEY_SECRET }}

      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: vpc-backoffice-stack
          template: euc-platform/cloudformation/vpc-eu-west-2-shared.yaml
          parameter-overrides: |
            ParameterKey1=ParameterValue1
            ParameterKey2=ParameterValue2
          capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
