name: Deploy Backoffice DCs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Directory Structure
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents cloudformation directory:"
          ls -la ./cloudformation/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: eu-west-2

      - name: Deploy Backoffice DCs
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dc-backoffice-stack
          template: ./cloudformation/dcs-eu-west-2-backoffice
          capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
          region: eu-west-2
